### PR TITLE
magicbox

### PR DESCRIPTION
**Pull request by Parth0248**
@namishkhanna

### CODE REVIEW

**Comment by Parth0248** [comment]
@namishkhanna i dont know how to make a separate pr for this ISBNinC....will this work ?? 
if not can u explain me how to make new pr ??
thanks

**Comment by namishkhanna** [comment]
what exactly you wanted to do ?

**Comment by Parth0248** [comment]
actually all the codes i pushed are displayed under same pull request...i was told by few other repos to make separate pr for each codes and i dont know how to...that is what i wanted to learn ...

**Comment by namishkhanna** [comment]
u have to create separate file for separate pull request

**Pull request merged**
